//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class EmailQueue
    {
        public int Id { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string SendTo { get; set; }
        public string Bcc { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public bool isFinish { get; set; }

        public EmailQueue()
        {
            Subject = "";
            Body = "";
            SendTo = "";
            Bcc = "";
            CreatedTime = DateTime.Now;
            isFinish = false;
        }
    }
    
}
