//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class Gallery
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public Nullable<int> OrderImage { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> CatalogID { get; set; }
    
        public virtual CatalogGallery CatalogGallery { get; set; }
    }
    
}
