//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Entities
{
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=CMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CatalogGallery> CatalogGalleries { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<EmailLog> EmailLogs { get; set; }
        public DbSet<EmailQueue> EmailQueues { get; set; }
        public DbSet<FileUpload> FileUploads { get; set; }
        public DbSet<Gallery> Galleries { get; set; }
        public DbSet<ListMail> ListMails { get; set; }
        public DbSet<Navigation> Navigations { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderActivity> OrderActivities { get; set; }
        public DbSet<OrderSize> OrderSizes { get; set; }
        public DbSet<OrderStatus> OrderStatus { get; set; }
        public DbSet<OrderType> OrderTypes { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<Slide> Slides { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Topic> Topics { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserInRole> UserInRoles { get; set; }
    }
}
