//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class OrderActivity
    {
        public int Id { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string FileLink { get; set; }
        public Nullable<int> UpdateByUserID { get; set; }
        public string Actions { get; set; }
        public string UpdateByUserName { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> Enable { get; set; }
        public string OrderName { get; set; }
        public Nullable<int> OrderUserID { get; set; }
        public string OrderUserName { get; set; }
    }
    
}
