//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int OrderById { get; set; }
        public string OrderByName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Size { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
        public string Link { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public Nullable<int> OrderPercent { get; set; }
        public string StaffID { get; set; }
        public string Parties { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ServiceType { get; set; }
        public string PartiesInformation { get; set; }
        public string BannerSize { get; set; }
        public string LatLng { get; set; }
    
        public virtual User User { get; set; }
    }
    
}
