//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Entities
{
    public partial class Party
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int AssignById { get; set; }
        public string AssignByName { get; set; }
        public string EmailAssigned { get; set; }
        public System.DateTime DateAssign { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
    
}
